version: '3'

services:
  backend:
    build: ./backend
    ports:
      - 8080:8080
    depends_on:
      - atha_yoga_db

  atha_yoga_db:
    image: postgres:14
    container_name: db
    environment:
      - ./backend/config/db/.env.example
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgres/data
