version: '3'

services:
  server:
    build: backend/
    container_name: backend
    env_file:
      - "${ENV_FILE}"
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend/static:/opt/services/backend/src/static
    depends_on:
      - db

  frontend:
    build: frontend/
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:8080"

  db:
    image: postgres:14
    container_name: db
    env_file:
      - "${ENV_FILE}"
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./db:/var/lib/postgres/data

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:v4.4.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${DOZZLE_PORT}:${DOZZLE_PORT}"
    environment:
      - "DOZZLE_ADDR=:${DOZZLE_PORT}"

  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: elasticsearch
    env_file:
      - "${ENV_FILE}"
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    volumes:
      - .devops/build/hunspell:/usr/share/elasticsearch/config/hunspell
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true
      - ES_JAVA_OPTS=-Xms750m -Xmx750m
