default_stages: [ commit ]

repos:
  - repo: local
    hooks:
      - id: black
        name: Running black
        entry: black
        exclude: '^.*\b(migrations)\b.*$'
        language: system
        files: .*.py
      - id: flake8
        name: Running flake8
        entry: flake8 --count
        language: system
        files: .*.py
        exclude: '^.*\b(migrations)\b.*$'
      - id: mypy
        name: Running mypy
        entry: mypy
        language: system
        files: .*.py
        exclude: '^.*\b(migrations|.ini|tests)\b.*$'