version: '3.7'

services:
  yoga_web:
    build: .
    command: python /usr/src/yoga/yoga/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/yoga
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    env_file:
      - ./.env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"