services:
  backend:
    container_name: backend
    env_file: .env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    env_file: .env
    container_name: db
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: